### DISCUSSION TITLE
Mount --user-data-dir for container

### DISCUSSION THREAD

**Discussion by phit42** [dgtlmoon/sockpuppetbrowser#13] [Announcements]
I was trying to follow this suggestion (for my docker container install of sockpupp on a Synology NAS):

> Don't burn out your disk!! Mount the path for --user-data-dir as a RAM Disk/tmpfs disk ! This will also help to speed up Chrome

so I mounted a directory /volumeSATA/satashare/.../user-data-dir from an external sata drive (I cannot "ram" it but at least I can move it away from my raid drives), 
`-v /volumeSATA/satashare/.../user-data-dir:/user-data-dir:rw`
and told Chromium to use it (env CHROMIUM_FLAGS  --user-data-dir=/user-data-dir ).

It doesn't work though. it doesn't recognize the flag or the directory, what am I missing?

**Comment by marrrc** [comment]
I did it like this (docker-compose) and it seems to be written to:

```
volumes:
  - type: tmpfs
     target: /tmp/cache
     tmpfs:
       size: 1000000000`
```

and then my flag would be `--user-data-dir=/tmp/cache`

**Reply by lordraiden** [reply]
> volumes:
>   - type: tmpfs
>      target: /tmp/cache
>      tmpfs:
>        size: 1000000000`

Where do you put this flag in the compose? this is mine


```
  sockpuppetbrowser:
    container_name: SockPuppetBrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    <<: [*config, *dns, *sec]
    networks:
      eth1:
        ipv4_address: ${sockpuppetbrowser_ip}
    ports:
        - 3000:3000
        - 8080:8080
    volumes:
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000`
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
```

**Reply by phit42** [reply]
Thank you @marrrc @lordraiden . This utilises the system's tmp directory to cache the information. tmp on my system is not big enough, thus I wanted to move it to a separate directory (on a mounted volume). Any idea why that wouldn't work?

**Comment by gilbrotheraway** [comment]
> I was trying to follow this suggestion (for my docker container install of sockpupp on a Synology NAS):
> 
> > Don't burn out your disk!! Mount the path for --user-data-dir as a RAM Disk/tmpfs disk ! This will also help to speed up Chrome
> 
> so I mounted a directory /volumeSATA/satashare/.../user-data-dir from an external sata drive (I cannot "ram" it but at least I can move it away from my raid drives), `-v /volumeSATA/satashare/.../user-data-dir:/user-data-dir:rw` and told Chromium to use it (env CHROMIUM_FLAGS --user-data-dir=/user-data-dir ).
> 
> It doesn't work though. it doesn't recognize the flag or the directory, what am I missing?

you were missing a "=" in:
CHROMIUM_FLAGS

**Reply by chicocheco** [reply]
Does it work for preserving cookies between rechecks?

**Comment by chicocheco** [comment]
This is my docker-compose.yml and it does not work. In the logs it says `2026-03-10 14:10:40.252 | DEBUG    | __main__:launchPuppeteerChromeProxy:450 - WebSocket ID: 0c690686-9b0f-443a-8708-693fff994393 Got new incoming connection ID from 172.23.0.3:35690 (/?timeout=603000)
2026-03-10 14:10:40.253 | DEBUG    | __main__:launch_chrome:162 - No --window-size in start query, falling back to env var --window-size=1920,1024
2026-03-10 14:10:40.268 | DEBUG    | __main__:launch_chrome:176 - No user-data-dir in query, using /tmp/chrome-puppeteer-proxygbwna1rg`. Not even `/tmp/chrome-puppeteer-proxygbwna1rg` is there. It does not create it.

So all environment variables in browser-sockpuppet-chrome are simply ignored? On the other hand if I add the flags to the URL like this `PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000/?--window-size=1920,1024&--user-data-dir=/home/my_user/changedetection/user-data-dir` it says it does not have permission to create the folder user-data-dir even when it is created already.

```
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - changedetection-data:/datastore
      environment:
        - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000/
      ports:
        - 172.24.24.24:5000:5000
      restart: unless-stopped
      depends_on:
          browser-sockpuppet-chrome:
              condition: service_started

    browser-sockpuppet-chrome:
      hostname: browser-sockpuppet-chrome
      image: dgtlmoon/sockpuppetbrowser:latest
      cap_add:
        - SYS_ADMIN
      restart: unless-stopped
      environment:
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1024
        - SCREEN_DEPTH=16
        - MAX_CONCURRENT_CHROME_PROCESSES=10
        - STATS_REFRESH_SECONDS=120
        - CHROMIUM_FLAGS=--user-data-dir=/home/my_user/changedetection/user-data-dir

volumes:
  changedetection-data:
```
How do I grant it the permission? I have tried everything. Thanks

**Comment by amigthea** [comment]
I'm facing the same issue and can't find the proper syntax to change `--user-data-dir` flag
should be a sockpuppetbrowser/playwright environment variable right? but is named `CHROMIUM_FLAGS=` or `CHROME_FLAGS=` like reported [here](https://github.com/dgtlmoon/changedetection.io/discussions/3498#:~:text=CHROME%5FFLAGS%3D%2D)?
could be also set in the changedetection's `PLAYWRIGHT_DRIVER_URL` variable like this?
`PLAYWRIGHT_DRIVER_URL=ws://localhost:3000/?chrome_flags=--user-data-dir=/tmp/cache`

edit:
inspecting the sockpuppetbrowser envs I see that it has this by default
`CHROMIUM_FLAGS=--disable-software-rasterizer --disable-dev-shm-usage`
so I added this in my docker compose
`CHROMIUM_FLAGS=--disable-software-rasterizer --disable-dev-shm-usage --user-data-dir=/tmp/cache`
along with
```
    volumes:
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
```
it should be set up now right? is there a way to test that? it doesn't seems to use the /tmp/cache directory (no files or subdir created) during checks
