### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by thyeestes** [dgtlmoon/sockpuppetbrowser#15]
I am experiencing a strange issue with running this in a Podman container. When I use this image then I get ERR_NAME_NOT_RESOLVED error, e.g. with this site https://www.asuswrt-merlin.net/.

When I use a browserless image like ghcr.io/browserless/chrome:latest it renders just fine.

Any ideas how to solve?

Thanks

**Comment by dgtlmoon** [comment]
Hmm not enough information, can you show the whole docker-compose.yml ?

**Comment by thyeestes** [comment]
Sure. However I am using Podman quadlets:
`[Container]
#Image=ghcr.io/browserless/chrome:latest
Image=docker.io/dgtlmoon/sockpuppetbrowser:latest
AddCapability=SYS_ADMIN
AutoUpdate=registry
ContainerName=cd-browserless
Network=proxy.network
Environment=TZ=Europe/Amsterdam
Environment=SCREEN_WIDTH=1920
Environment=SCREEN_HEIGHT=1080
Environment=SCREEN_DEPTH=24
Environment=MAX_CONCURRENT_CHROME_PROCESSES=10
Environment=ENABLE_DEBUGGER=false
Environment=PREBOOT_CHROME=true
Environment=CONNECTION_TIMEOUT=300000
Environment=MAX_CONCURRENT_SESSIONS=10
Pod=changedetection.pod

[Container]
Image=docker.io/dgtlmoon/changedetection.io:latest
AutoUpdate=registry
ContainerName=cd-changedetection
Network=proxy.network
Volume=$PWD/changedetection:/datastore
Environment=TZ=Europe/Amsterdam
Environment=LOGGER_LEVEL=DEBUG
Environment=PLAYWRIGHT_DRIVER_URL=ws://cd-browserless:3000
#Environment=PLAYWRIGHT_DRIVER_URL=ws://cd-browserless:3000/chrome?launch={"headless":false}
Pod=changedetection.pod`

**Comment by skyblaster** [comment]
I'm also using a Podman quadlet with `Environment=PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000` and seeing the same `Exception: net::ERR_NAME_NOT_RESOLVED` 

My host is Fedora CoreOS and I see the last email received from changedetection.io was August 16th, with a host reboot on the 17th.

This appears to be a Podman, netavark, and/or passt issue. I just opened the following hoping the FCOS team can reproduce the issue and possibly expedite the promotion of testing to stable : https://github.com/coreos/fedora-coreos-tracker/issues/1790

**Comment by thyeestes** [comment]
I switched to slirp4netns, because of an issue with socket activation and Traefik, so I think you can take passt out of equation.

**Comment by AnderssonPeter** [comment]
I'm having the same issue, I'm running on NixOS with docker..

And I'm fairy certain it's something inside this container that causes the issue, if I jump into it and run
```
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Network unreachable
```

If I do the exact same thing inside changedetection it works as expected:
```
ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=111 time=11.7 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=111 time=11.2 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=111 time=11.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=111 time=11.3 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=111 time=11.3 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=111 time=11.2 ms
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5007ms
rtt min/avg/max/mdev = 11.211/11.341/11.659/0.150 ms
```

**Comment by robinvalk** [comment]
I had the same problem and I just discovered after an hour of debugging that I had the "internal" network marked as `internal: true` and therefore the browser container was not allowed to reach the internet 🤦‍♂️ .

Before:
```
  ...

  sockpuppetbrowser:
    image: dgtlmoon/sockpuppetbrowser:latest
    ...
    networks:
      - changedetection-internal

networks:
  proxy:
    external: true
  changedetection-internal:
    internal: true
```

After:
```
  ...

  sockpuppetbrowser:
    image: dgtlmoon/sockpuppetbrowser:latest
    ...
    networks:
      - changedetection-internal

networks:
  proxy:
    external: true
  changedetection-internal:
```

**Comment by APT37** [comment]
Same problem here. Only the `sockpuppetbrowser` is affected, any other service with this configuration works as expected. The normal `changedetection.io` checks also succeed.

```
services:
  changedetection-io:
    image: dgtlmoon/changedetection.io:latest
    container_name: changedetection-io
    restart: unless-stopped
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000
    volumes:
      - ./config:/config

  sockpuppetbrowser:
    image: dgtlmoon/sockpuppetbrowser:latest
    container_name: sockpuppetbrowser
    restart: unless-stopped
    environment:
      - DEFAULT_LAUNCH_ARGS="--window-size=1920,1080"

networks:
  default:
    external: true
    name: internal
```
