### ISSUE TITLE
FEATURE REQUEST: Custom Port Numbers

### ISSUE THREAD

**Issue by jeremymeyers** [dgtlmoon/sockpuppetbrowser#23]
Both port 3000 and port 8080 are in use on my server, so being able to pick different ports via environment variable would be very useful, especially since you can customize the port in the main changedetection docker-compose.yml

**Comment by seth100** [comment]
I'd need this feature too 🙏🏼

**Comment by seth100** [comment]
I found the way to do that in `docker-compose.yml`: `command: ["/usr/local/bin/entrypoint.sh", "--sport", "<new-port>"]`

**Comment by opicron** [comment]
You can reset the ports like so in docker-compose.reset.yml:
```
services:
  app:
    ports: !reset []
```

Then redefine them as such in docker-compose.override.yml:
```
services:
  app:
    container_name: sockpuppetbrowser
    ports: !override
      - 3077:3000 
      - 8077:8080 
```

Createdocker as such:

`docker-compose -f docker-compose.yml -f ../docker-compose.reset.yml -f ../docker-compose.override.yml up -d`

Edit: this "issue" should be closed imho.
